name: dart_cpp_binding_generator
dependencies:
  build: ^0.12.0
  build_config: ^0.2.0
  c_builder: ^1.0.0
  dart_cpp_binding_annotation:
    path: ../dart_cpp_binding_annotation
  recase: ^1.0.0
  source_gen: ^0.8.0
dev_dependencies:
  build_runner: ^0.8.0
  test: ^0.12.0