name: dart_cpp_binding_generator
dependencies:
  build: ">=0.12.0 <2.0.0"
  build_config: ^0.3.0
  c_builder: ^1.0.0
  dart_cpp_binding_annotation:
    path: ../dart_cpp_binding_annotation
  recase: ^2.0.0
  source_gen: ^0.9.0
dev_dependencies:
  build_runner: ^1.0.0
  test: ^1.0.0