targets:
  $default: {}
builders:
  cpp_binding:
    target: "cpp_binding_generator"
    import: "package:cpp_binding_generator/cpp_binding_generator.dart"
    builder_factories:
      - cppBindingClassBuilder
      - extensionBuilder
    auto_apply: root_package
    build_to: source
    build_extensions:
      .dart:
        - .extension.g.hpp
        - .extension.g.cpp
        - .g.hpp
        - .g.cpp